# Copyright (c) 2025 Tearnote (Hubert Maraszek)
#
# Licensed under the Mozilla Public License Version 2.0 <LICENSE-MPL-2.0.txt
# or https://www.mozilla.org/en-US/MPL/2.0/> or the Boost Software License <LICENSE-BSL-1.0.txt
# or https://www.boost.org/LICENSE_1_0.txt>, at your option. This file may not be copied, modified,
# or distributed except according to those terms.

name: Windows build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  packages: write

env:
  BUILD_TYPE: Release
  VCPKG_TARGET_TRIPLET: x64-windows-static-md
  USERNAME: Tearnote
  FEED_URL: https://nuget.pkg.github.com/Tearnote/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/Tearnote/index.json,readwrite"

jobs:
  windows-build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: Add NuGet sources
        shell: pwsh
        run: |
          $vcpkg = "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe"
          $nuget = & $vcpkg fetch nuget | Select-Object -Last 1
          & $nuget sources add `
            -Source "${{env.FEED_URL}}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{env.USERNAME}}" `
            -Password "${{secrets.GITHUB_TOKEN}}"
          & $nuget setapikey "${{secrets.GITHUB_TOKEN}}" `
            -Source "${{env.FEED_URL}}"

      - name: Configure CMake
        shell: cmd
        run: cmake -B ${{github.workspace}}/build -T ClangCL -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{env.VCPKG_TARGET_TRIPLET}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playnote-windows-build
          path: ${{github.workspace}}/build/install/${{env.BUILD_TYPE}}
